create table if not exists public.payment_orders (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  payment_method text not null,
  payment_status text not null,
  currency text not null default 'INR',
  amount numeric(10, 2) not null,
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  address text not null,
  city text,
  pincode text,
  items jsonb not null,
  razorpay_order_id text,
  razorpay_payment_id text,
  razorpay_signature text,
  created_at timestamptz not null default now()
);

create index if not exists payment_orders_created_at_idx
  on public.payment_orders (created_at desc);

create index if not exists payment_orders_payment_status_idx
  on public.payment_orders (payment_status);
